from decimal import Decimal

from core.business_modules import BusinessType, normalize_business_type

INVENTORY_STARTER_ITEMS = [
    {
        "sku": "PPE-GLOVES-NITRILE",
        "name": "Gants nitrile",
        "category": "Protection",
        "unit": "boite",
        "min_stock_level": 30,
        "notes": "Gants d'examen non steriles pour soins courants.",
    },
    {
        "sku": "PPE-MASK-SURG",
        "name": "Masques chirurgicaux",
        "category": "Protection",
        "unit": "boite",
        "min_stock_level": 20,
        "notes": "Masques pour l'equipe et les actes cliniques quotidiens.",
    },
    {
        "sku": "PPE-FACE-SHIELD",
        "name": "Visieres de protection",
        "category": "Protection",
        "unit": "unite",
        "min_stock_level": 6,
        "notes": "Protection contre projections et aerosols.",
    },
    {
        "sku": "INF-SURFACE-WIPES",
        "name": "Lingettes de desinfection surfaces",
        "category": "Infection control",
        "unit": "boite",
        "min_stock_level": 12,
        "notes": "Nettoyage rapide des surfaces entre patients.",
    },
    {
        "sku": "INF-HAND-RUB",
        "name": "Solution hydroalcoolique",
        "category": "Infection control",
        "unit": "flacon",
        "min_stock_level": 10,
        "notes": "Hygiene des mains pour zones cliniques et accueil.",
    },
    {
        "sku": "INF-STERI-POUCH",
        "name": "Sachets de sterilisation",
        "category": "Sterilisation",
        "unit": "boite",
        "min_stock_level": 8,
        "notes": "Conditionnement des instruments avant sterilisation.",
    },
    {
        "sku": "INF-AUTOCLAVE-IND",
        "name": "Indicateurs de sterilisation",
        "category": "Sterilisation",
        "unit": "boite",
        "min_stock_level": 4,
        "notes": "Controle des cycles de sterilisation.",
    },
    {
        "sku": "CONS-COTTON-ROLL",
        "name": "Rouleaux de coton",
        "category": "Consommables",
        "unit": "paquet",
        "min_stock_level": 10,
        "notes": "Isolation et assèchement pendant les soins.",
    },
    {
        "sku": "CONS-SUCTION-TIPS",
        "name": "Embouts d'aspiration",
        "category": "Consommables",
        "unit": "paquet",
        "min_stock_level": 10,
        "notes": "Embouts jetables pour aspiration salivaire.",
    },
    {
        "sku": "CONS-NEEDLES",
        "name": "Aiguilles dentaires",
        "category": "Anesthesie",
        "unit": "boite",
        "min_stock_level": 6,
        "notes": "Aiguilles courtes et longues selon protocole clinique.",
    },
    {
        "sku": "PHAR-LOCAL-ANESTH",
        "name": "Anesthesique local carpules",
        "category": "Anesthesie",
        "unit": "boite",
        "min_stock_level": 8,
        "notes": "Carpules d'anesthesie locale pour actes courants.",
    },
    {
        "sku": "REST-COMPOSITE-A2",
        "name": "Composite teinte A2",
        "category": "Restauration",
        "unit": "seringue",
        "min_stock_level": 6,
        "notes": "Materiau de restauration directe teinte universelle.",
    },
    {
        "sku": "REST-BONDING",
        "name": "Adhesif dentaire",
        "category": "Restauration",
        "unit": "flacon",
        "min_stock_level": 3,
        "notes": "Systeme adhesif pour restaurations composites.",
    },
    {
        "sku": "REST-GLASS-IONOMER",
        "name": "Ciment verre ionomere",
        "category": "Restauration",
        "unit": "kit",
        "min_stock_level": 3,
        "notes": "Restaurations temporaires, scellements et indications pediatriques.",
    },
    {
        "sku": "ENDO-FILES-K",
        "name": "Limes endodontiques K",
        "category": "Endodontie",
        "unit": "boite",
        "min_stock_level": 4,
        "notes": "Instrumentation manuelle pour traitement canalaire.",
    },
    {
        "sku": "ENDO-GUTTA",
        "name": "Pointes de gutta-percha",
        "category": "Endodontie",
        "unit": "boite",
        "min_stock_level": 4,
        "notes": "Obturation canalaire.",
    },
    {
        "sku": "PERIO-SCALER-TIPS",
        "name": "Inserts detartreur ultrasonique",
        "category": "Parodontologie",
        "unit": "unite",
        "min_stock_level": 6,
        "notes": "Detartrage et maintenance parodontale.",
    },
    {
        "sku": "SURG-SUTURE-RESORB",
        "name": "Sutures resorbables",
        "category": "Chirurgie",
        "unit": "boite",
        "min_stock_level": 4,
        "notes": "Sutures pour extractions et chirurgie orale simple.",
    },
    {
        "sku": "SURG-SCALPEL-BLADES",
        "name": "Lames de bistouri",
        "category": "Chirurgie",
        "unit": "boite",
        "min_stock_level": 3,
        "notes": "Chirurgie orale et parodontale.",
    },
    {
        "sku": "RAD-SENSOR-SHEATH",
        "name": "Protections capteur radio",
        "category": "Radiologie",
        "unit": "boite",
        "min_stock_level": 6,
        "notes": "Barrieres jetables pour capteur intraoral.",
    },
    {
        "sku": "IMP-ALGINATE",
        "name": "Alginate empreinte",
        "category": "Empreintes",
        "unit": "sachet",
        "min_stock_level": 4,
        "notes": "Empreintes preliminaires et modeles d'etude.",
    },
    {
        "sku": "IMP-VPS",
        "name": "Silicone VPS empreinte",
        "category": "Empreintes",
        "unit": "cartouche",
        "min_stock_level": 4,
        "notes": "Empreintes de precision prothese et couronnes.",
    },
    {
        "sku": "PREV-FLUORIDE-GEL",
        "name": "Gel fluore",
        "category": "Prevention",
        "unit": "flacon",
        "min_stock_level": 4,
        "notes": "Application topique preventive.",
    },
    {
        "sku": "PREV-SEALANT",
        "name": "Sealant sillons",
        "category": "Prevention",
        "unit": "seringue",
        "min_stock_level": 3,
        "notes": "Scellement preventif des sillons.",
    },
]

DENTAL_INVENTORY_STARTER_ITEMS = INVENTORY_STARTER_ITEMS

PHONE_STORE_INVENTORY_STARTER_ITEMS = [
    {
        "sku": "PHONE-IPHONE-BASE",
        "name": "Smartphone iOS entree de gamme",
        "category": "Phones",
        "unit": "unite",
        "min_stock_level": 2,
        "notes": "Modele iOS courant pour demarrer le catalogue telephonie.",
    },
    {
        "sku": "PHONE-ANDROID-BASE",
        "name": "Smartphone Android entree de gamme",
        "category": "Phones",
        "unit": "unite",
        "min_stock_level": 3,
        "notes": "Modele Android courant pour ventes rapides.",
    },
    {
        "sku": "PHONE-ANDROID-MID",
        "name": "Smartphone Android milieu de gamme",
        "category": "Phones",
        "unit": "unite",
        "min_stock_level": 2,
        "notes": "Produit principal pour stock polyvalent.",
    },
    {
        "sku": "ACC-EARBUDS-BT",
        "name": "Ecouteurs Bluetooth",
        "category": "Accessories",
        "unit": "unite",
        "min_stock_level": 8,
        "notes": "Accessoire a rotation rapide.",
    },
    {
        "sku": "ACC-CASE-UNIVERSAL",
        "name": "Coque de protection universelle",
        "category": "Accessories",
        "unit": "unite",
        "min_stock_level": 20,
        "notes": "Coques standards pour modeles populaires.",
    },
    {
        "sku": "CHG-USB-C-20W",
        "name": "Chargeur USB-C 20W",
        "category": "Chargers",
        "unit": "unite",
        "min_stock_level": 12,
        "notes": "Chargeur secteur rapide compatible appareils recents.",
    },
    {
        "sku": "CHG-CAR-USB-C",
        "name": "Chargeur voiture USB-C",
        "category": "Chargers",
        "unit": "unite",
        "min_stock_level": 6,
        "notes": "Chargeur allume-cigare pour ventes complementaires.",
    },
    {
        "sku": "CBL-USB-C-1M",
        "name": "Cable USB-C 1m",
        "category": "Cables",
        "unit": "unite",
        "min_stock_level": 25,
        "notes": "Cable de charge standard.",
    },
    {
        "sku": "CBL-LIGHTNING-1M",
        "name": "Cable Lightning 1m",
        "category": "Cables",
        "unit": "unite",
        "min_stock_level": 15,
        "notes": "Cable compatible appareils iOS.",
    },
    {
        "sku": "PROT-TEMPERED-GLASS",
        "name": "Protection ecran verre trempe",
        "category": "Screen protectors",
        "unit": "unite",
        "min_stock_level": 30,
        "notes": "Protection ecran generique pour formats populaires.",
    },
]

DROGUERIE_INVENTORY_STARTER_ITEMS = [
    {
        "sku": "HW-SCREWS-ASSORT",
        "name": "Assortiment visserie",
        "category": "Hardware products",
        "unit": "boite",
        "min_stock_level": 10,
        "notes": "Vis courantes pour bricolage et petites reparations.",
    },
    {
        "sku": "HW-NAILS-ASSORT",
        "name": "Assortiment clous",
        "category": "Hardware products",
        "unit": "boite",
        "min_stock_level": 8,
        "notes": "Clous tailles mixtes pour usage domestique.",
    },
    {
        "sku": "HW-ADHESIVE-TAPE",
        "name": "Ruban adhesif multi-usage",
        "category": "Hardware products",
        "unit": "rouleau",
        "min_stock_level": 12,
        "notes": "Ruban pour reparations rapides et emballage.",
    },
    {
        "sku": "HOME-DETERGENT",
        "name": "Detergent menager",
        "category": "Household products",
        "unit": "bidon",
        "min_stock_level": 10,
        "notes": "Produit d'entretien courant.",
    },
    {
        "sku": "HOME-DISINFECTANT",
        "name": "Desinfectant surfaces",
        "category": "Household products",
        "unit": "flacon",
        "min_stock_level": 12,
        "notes": "Nettoyage et hygiene des surfaces.",
    },
    {
        "sku": "HOME-SPONGES",
        "name": "Eponges menageres",
        "category": "Household products",
        "unit": "paquet",
        "min_stock_level": 20,
        "notes": "Consommable a rotation rapide.",
    },
    {
        "sku": "TOOL-SCREWDRIVER-SET",
        "name": "Jeu de tournevis",
        "category": "Tools",
        "unit": "set",
        "min_stock_level": 5,
        "notes": "Outil de base pour rayon bricolage.",
    },
    {
        "sku": "TOOL-PLIERS",
        "name": "Pince universelle",
        "category": "Tools",
        "unit": "unite",
        "min_stock_level": 4,
        "notes": "Outil polyvalent pour clients particuliers.",
    },
    {
        "sku": "CONS-GLOVES-WORK",
        "name": "Gants de travail",
        "category": "Consumables",
        "unit": "paire",
        "min_stock_level": 15,
        "notes": "Protection pour bricolage et manutention.",
    },
    {
        "sku": "CONS-BATTERIES-AA",
        "name": "Piles AA",
        "category": "Consumables",
        "unit": "paquet",
        "min_stock_level": 20,
        "notes": "Consommable courant pour droguerie.",
    },
]

RETAIL_INVENTORY_STARTER_ITEMS = [
    {
        "sku": "RET-GENERIC-PRODUCT",
        "name": "Produit standard",
        "category": "Products",
        "unit": "unite",
        "min_stock_level": 10,
        "notes": "Article generique a adapter au commerce.",
    },
    {
        "sku": "RET-ACCESSORY",
        "name": "Accessoire",
        "category": "Accessories",
        "unit": "unite",
        "min_stock_level": 10,
        "notes": "Accessoire de vente additionnelle.",
    },
    {
        "sku": "RET-CONSUMABLE",
        "name": "Consommable",
        "category": "Consumables",
        "unit": "paquet",
        "min_stock_level": 12,
        "notes": "Consommable recurrent pour stock de base.",
    },
    {
        "sku": "RET-PACKAGING-BAG",
        "name": "Sacs d'emballage",
        "category": "Packaging",
        "unit": "paquet",
        "min_stock_level": 20,
        "notes": "Emballage client pour point de vente.",
    },
    {
        "sku": "RET-PACKAGING-LABEL",
        "name": "Etiquettes prix",
        "category": "Packaging",
        "unit": "rouleau",
        "min_stock_level": 5,
        "notes": "Etiquetage prix et references produits.",
    },
]


TREATMENT_TEMPLATES = [
    {
        "code": "CONS-EXAM",
        "category": "Diagnostic",
        "name": "Consultation et examen bucco-dentaire",
        "description": "Examen clinique, anamnese et plan d'orientation.",
        "estimated_cost": Decimal("200"),
        "priority": "normal",
    },
    {
        "code": "RAD-PA",
        "category": "Diagnostic",
        "name": "Radiographie retro-alveolaire",
        "description": "Cliche intraoral cible pour diagnostic localise.",
        "estimated_cost": Decimal("80"),
        "priority": "normal",
    },
    {
        "code": "RAD-PANO",
        "category": "Diagnostic",
        "name": "Radiographie panoramique",
        "description": "Bilan radiographique global avant planification.",
        "estimated_cost": Decimal("250"),
        "priority": "normal",
    },
    {
        "code": "PREV-SCALING",
        "category": "Prevention",
        "name": "Detartrage et polissage",
        "description": "Elimination du tartre supra-gingival et polissage.",
        "estimated_cost": Decimal("350"),
        "priority": "normal",
    },
    {
        "code": "PREV-FLUORIDE",
        "category": "Prevention",
        "name": "Application de fluor",
        "description": "Application topique pour prevention carieuse.",
        "estimated_cost": Decimal("150"),
        "priority": "low",
    },
    {
        "code": "REST-COMP",
        "category": "Restauration",
        "name": "Obturation composite",
        "description": "Restauration directe d'une lesion carieuse.",
        "estimated_cost": Decimal("450"),
        "priority": "normal",
    },
    {
        "code": "REST-GIC",
        "category": "Restauration",
        "name": "Obturation verre ionomere",
        "description": "Restauration temporaire ou indication specifique.",
        "estimated_cost": Decimal("300"),
        "priority": "normal",
    },
    {
        "code": "PROS-CROWN",
        "category": "Prothese",
        "name": "Couronne dentaire",
        "description": "Preparation, empreinte et pose d'une couronne.",
        "estimated_cost": Decimal("2500"),
        "priority": "normal",
    },
    {
        "code": "ENDO-SINGLE",
        "category": "Endodontie",
        "name": "Traitement endodontique monoradiculaire",
        "description": "Traitement canalaire d'une dent monoradiculaire.",
        "estimated_cost": Decimal("1200"),
        "priority": "high",
    },
    {
        "code": "ENDO-MULTI",
        "category": "Endodontie",
        "name": "Traitement endodontique pluriradiculaire",
        "description": "Traitement canalaire d'une molaire ou dent pluriradiculaire.",
        "estimated_cost": Decimal("1800"),
        "priority": "high",
    },
    {
        "code": "PERIO-SRP",
        "category": "Parodontologie",
        "name": "Surfacage radiculaire",
        "description": "Therapie parodontale non chirurgicale par quadrant.",
        "estimated_cost": Decimal("800"),
        "priority": "high",
    },
    {
        "code": "SURG-EXT",
        "category": "Chirurgie",
        "name": "Extraction simple",
        "description": "Avulsion dentaire simple sous anesthesie locale.",
        "estimated_cost": Decimal("500"),
        "priority": "high",
    },
    {
        "code": "SURG-EXT-CPLX",
        "category": "Chirurgie",
        "name": "Extraction chirurgicale",
        "description": "Avulsion complexe avec geste chirurgical.",
        "estimated_cost": Decimal("1200"),
        "priority": "high",
    },
    {
        "code": "IMPL-CONSULT",
        "category": "Implantologie",
        "name": "Consultation implantologie",
        "description": "Evaluation pre-implantaire et planification.",
        "estimated_cost": Decimal("400"),
        "priority": "normal",
    },
    {
        "code": "AESTH-WHITENING",
        "category": "Esthetique",
        "name": "Blanchiment dentaire",
        "description": "Traitement eclaircissant selon indication clinique.",
        "estimated_cost": Decimal("1800"),
        "priority": "low",
    },
]

INVENTORY_STARTER_ITEMS_BY_BUSINESS_TYPE = {
    BusinessType.DENTAL_CLINIC: DENTAL_INVENTORY_STARTER_ITEMS,
    BusinessType.PHONE_STORE: PHONE_STORE_INVENTORY_STARTER_ITEMS,
    BusinessType.DROGUERIE: DROGUERIE_INVENTORY_STARTER_ITEMS,
    BusinessType.RETAIL: RETAIL_INVENTORY_STARTER_ITEMS,
}

CATALOG_METADATA_BY_BUSINESS_TYPE = {
    BusinessType.DENTAL_CLINIC: {
        "title": "Catalogue recommande pour cabinet dentaire",
        "description": "Consommables, protection, sterilisation, restauration, endodontie et chirurgie de base.",
    },
    BusinessType.PHONE_STORE: {
        "title": "Catalogue recommande pour magasin de telephonie",
        "description": "Telephones, accessoires, chargeurs, cables et protections ecran.",
    },
    BusinessType.DROGUERIE: {
        "title": "Catalogue recommande pour droguerie",
        "description": "Quincaillerie, produits menagers, outils et consommables courants.",
    },
    BusinessType.RETAIL: {
        "title": "Catalogue recommande pour commerce",
        "description": "Produits, accessoires, consommables et emballages de base.",
    },
}


def get_inventory_starter_items(business_type: str | None) -> list[dict]:
    normalized = normalize_business_type(business_type)
    return list(INVENTORY_STARTER_ITEMS_BY_BUSINESS_TYPE[normalized])


def get_treatment_templates(business_type: str | None) -> list[dict]:
    if normalize_business_type(business_type) != BusinessType.DENTAL_CLINIC:
        return []
    return list(TREATMENT_TEMPLATES)


def get_catalog_metadata(business_type: str | None) -> dict[str, str]:
    normalized = normalize_business_type(business_type)
    return dict(CATALOG_METADATA_BY_BUSINESS_TYPE[normalized])
