from core.middleware.auth.permission_list import Permission, Role

ALL_PERMISSIONS = {
    Permission.PATIENTS_READ,
    Permission.PATIENTS_CREATE,
    Permission.PATIENTS_UPDATE,
    Permission.PATIENTS_DELETE,
    Permission.APPOINTMENTS_READ,
    Permission.APPOINTMENTS_MANAGE,
    Permission.DENTAL_CHART_READ,
    Permission.DENTAL_CHART_MANAGE,
    Permission.TREATMENTS_READ,
    Permission.TREATMENTS_MANAGE,
    Permission.BILLING_READ,
    Permission.BILLING_MANAGE,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_MANAGE,
    Permission.REPORTS_VIEW,
    Permission.SETTINGS_MANAGE,
    Permission.STAFF_MANAGE,
    Permission.CLINICS_MANAGE,
    Permission.DOCUMENTS_READ,
    Permission.DOCUMENTS_MANAGE,
    Permission.NOTIFICATIONS_READ,
    Permission.NOTIFICATIONS_MANAGE,
    Permission.ITEMS_READ,
    Permission.ITEMS_WRITE,
    Permission.ITEMS_DELETE,
}

ROLE_PERMISSIONS: dict[str, set[str]] = {
    Role.OWNER: ALL_PERMISSIONS,
    Role.ADMIN: ALL_PERMISSIONS - {Permission.SETTINGS_MANAGE},
    Role.DENTIST: {
        Permission.PATIENTS_READ,
        Permission.PATIENTS_CREATE,
        Permission.PATIENTS_UPDATE,
        Permission.APPOINTMENTS_READ,
        Permission.APPOINTMENTS_MANAGE,
        Permission.DENTAL_CHART_READ,
        Permission.DENTAL_CHART_MANAGE,
        Permission.TREATMENTS_READ,
        Permission.TREATMENTS_MANAGE,
        Permission.BILLING_READ,
        Permission.DOCUMENTS_READ,
        Permission.DOCUMENTS_MANAGE,
        Permission.NOTIFICATIONS_READ,
        Permission.NOTIFICATIONS_MANAGE,
        Permission.REPORTS_VIEW,
    },
    Role.ASSISTANT: {
        Permission.PATIENTS_READ,
        Permission.PATIENTS_UPDATE,
        Permission.APPOINTMENTS_READ,
        Permission.APPOINTMENTS_MANAGE,
        Permission.DENTAL_CHART_READ,
        Permission.TREATMENTS_READ,
        Permission.TREATMENTS_MANAGE,
        Permission.DOCUMENTS_READ,
        Permission.DOCUMENTS_MANAGE,
        Permission.NOTIFICATIONS_READ,
        Permission.NOTIFICATIONS_MANAGE,
    },
    Role.RECEPTIONIST: {
        Permission.PATIENTS_READ,
        Permission.PATIENTS_CREATE,
        Permission.PATIENTS_UPDATE,
        Permission.APPOINTMENTS_READ,
        Permission.APPOINTMENTS_MANAGE,
        Permission.BILLING_READ,
        Permission.BILLING_MANAGE,
        Permission.DOCUMENTS_READ,
        Permission.NOTIFICATIONS_READ,
        Permission.NOTIFICATIONS_MANAGE,
    },
    Role.USER: {Permission.ITEMS_READ, Permission.ITEMS_WRITE},
    Role.VIEWER: {Permission.ITEMS_READ},
}
